### PR TITLE
Update German mail hosters

### PR DESCRIPTION
**Pull request by Djfe**
If you have any questions regarding the changes, don't hesitate to ask :)
Details are explained in the commit messages.

### CODE REVIEW

**Comment by Djfe** [comment]
Maybe @Hagen-Ionos could help out with the IONOS commit. I only now noticed his/her PR from 2021.
The thing is: I couldn't find any domains out there. Is it only possible to get mails from your own domain or actually possible to book `somethingxyz@ionos.de`? I couldn't figure this out without ordering from them

**Comment by benbucksch** [comment]
Let's discuss Ionos in the other pull request.
It's good to have one PR per topic.

**Comment by Djfe** [comment]
agreed

**Comment by benbucksch** [comment]
@Djfe Hey Felix, thanks a lot for these updates! Would you mind filing one PR per ISP? Like that, it's easier to discuss, verify, and the commit log is also cleaner. Thank you!

**Pull request closed without merging**
