### PR TITLE
Add autoconfig documentation

### PR DESCRIPTION
**Pull request by cketti**
@SphinxKnight converted the archived HTML to Markdown and created a [pull request on developer-docs](https://github.com/thundernest/developer-docs/pull/158). We've discussed this internally and came to the conclusion that this repository would be a better place for the documentation.

This pull request only adds the Markdown source for the documentation. In a second step the deployment script has to be updated to actually build the HTML site using Jekyll.

### CODE REVIEW

**Comment by benbucksch** [comment]
Please hold on this until I had the chance to review the state of the documents and discuss strategy here.
Also, this version is removing the authorship. This would need to be restored.

The current authorative documents are at https://www.bucksch.org/1/projects/thunderbird/autoconfiguration/

**Comment by SphinxKnight** [comment]
> Please hold on this until I had the chance to review the state of the documents and discuss strategy here.
> Also, this version is removing the authorship, which would need to be restored.

Please do restore, I removed it because initial PR was on DTN where no other pages had such autorship info + MDN history had more people for this page: (what follows is an excerpt of https://raw.githubusercontent.com/mdn/archived-content/main/files/en-us/_wikihistory.json)

```
  "Mozilla/Thunderbird/Autoconfiguration": {
    "modified": "2020-05-16T07:25:37.450Z",
    "contributors": [
      "BenB",
      "monperrus",
      "Violapark-droid",
      "rayksland",
      "dilyanpalauzov",
      "l_bratch",
      "SphinxKnight",
      "tedmarynicz",
      "tillz",
      "AndrewSutherland",
      "teoli",
      "so0k",
      "chrisdavidmills",
      "andykimpe",
      "openjck",
      "jswisher",
      "thesurf",
      "Standard8",
      "NickMaynard",
      "mooz",
      "larsrohr",
      "k.ghadami@ibson.com"
    ]
  },
```

**Comment by cketti** [comment]
I don't think including the name of everyone who touched the files is adding much value to readers of the documentation. If Ben wants to be mentioned as the initial author, I'd add a note to the bottom of the page, not the top.

**Comment by benbucksch** [comment]
I'm currently restoring the last known version of the docs and specs and formatting them using Markdown. Please hold until I have a PR.

**Comment by cketti** [comment]
@benbucksch: Please feel free to rewrite and force-push to this PR branch.

**Comment by benbucksch** [comment]
Thanks for this PR. It's a good idea to have the docs here. Unfortunately, the docs in this PR are a little outdated (and already were outdated at the time of submission), that's why I didn't merge it.

As for the build scripts, it's not clear to me who and how one would use them. Where would they be deployed? Given that they are generic .md docs, any converter of the admin's choice would do. For humans, github can display .md nicely as HTML. So, I am not sure we need that build script, unless we have a concrete use case.

**Pull request closed without merging**
